Algoritmo "Atividade 8 - 3"
// Autor(a)    : Hugo Henrique
// Data atual  : 12/09/2024
Var
// Seção de Declarações das variáveis 
 numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("digite um numero: ")
leia(numero)

se(numero > 0)entao
escreva("o valor positivo do seu valor é ", numero *2)
senao
escreva("o valor negativo do seu valor é ", numero *3)
fimse

Fimalgoritmo