Algoritmo "Atividade 07 - 03"
// Autor(a)    : Hugo Henrique
// Data atual  : 10/09/2024
Var
// Seção de Declarações das variáveis 
idade: inteiro
renda: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("qual sua idade: ")
leia(idade)

escreva("qual sua renda: ")
leia(renda)

escreval("com a sua idade e sua renda você pode? ", (idade>=18) E (renda>=1500))
Fimalgoritmo