Algoritmo "Atividade 9 - 1"
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/09/2024
Var
// Seção de Declarações das variáveis 
cores: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("1 -  vermelho")
escreval("2 -  amarelo")
escreval("3 -  verde")
leia(cores)

se(cores = 1)então
escreval("pare")
se(cores = 2)entao
escreval("atenção")
se(cores = 3)entao
escreval("siga")

fimse
fimse
fimse

Fimalgoritmo