Algoritmo "maior de idade"
// Autor(a)    : Hugo Henrique
// Data atual  : 05/09/2024
Var
// Seção de Declarações das variáveis 
nome: caractere
idade: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
nome <- "hugo"
idade <- 18

escreva("digite seu nome: ")
leia(nome)

escreva("escreva sua idade: ")
leia(idade)

escreval("você é maior de idade ", 18<=idade)

Fimalgoritmo