Algoritmo "que ano eu nasci"
// Autor(a)    : Hugo henrique
// Data atual  : 04/09/2024
Var
// Seção de Declarações das variáveis
nome: caractere
idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
nome <- "Hugo"
idade <- 18


escreva("qual o seu nome? ")
leia(nome)
escreval("olá ", nome, ", seja bem vindo!")

escreva("escreva sua idade: ")
leia (idade)
escreval ("você nasceu em", 2024-idade )




Fimalgoritmo