Algoritmo "soma dos numeros"
// Autor(a)    : Hugo Henrique
// Data atual  : 05/09/2024
Var
// Seção de Declarações das variáveis 
numero: real
numeroDois: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
numero <- 2500
numeroDois <- 2500


escreva("digite um numero: ")
leia(numero)

escreva("escreva outro numero: ")
leia(numeroDois)

escreval ("essa é a soma dos dois numeros escolhidos", numero+numeroDois)



Fimalgoritmo